name: manual push
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'version'
        required: true
        type: string

jobs:


  build_push_monolith:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 0



      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: martabal
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push immich
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/arm/v7,linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            martabal/qbitorrent-exporter:${{ inputs.tags }}
            martabal/qbitorrent-exporter:latest

